### ISSUE TITLE
Does libloading allow async code?

### ISSUE THREAD

**Issue by ra0x3** [nagisa/rust_libloading#114]
- Probably a dumb question, but asking because I read over https://github.com/nagisa/rust_libloading/issues/81 and got curious
- But does libloading support calling async functions?
- Meaning:
  - If I have a defined function `async fn foo()` in my library `my_lib`
  - Then I load `my_lib` via libloading
  - Then I call `foo` -- is there any way to make that call to `foo` `async`?

**Comment by nagisa** [comment]
So, first, `async fn foo() -> R { ... }` is just a sugar for `fn foo() -> Future<R> { async { ... } }`. In that sense, `async` functions are no different from regular functions, its just that their return type is a lil' different. And yeah, you can kinda load them with libloading, no problem.

The problem comes up when you got to ensure ABI stability. `fn bar()` is actually by itself equivalent to `extern "Rust" fn bar()`. The `"Rust"` ABI is not specified, and pretty much the only way to guarantee compatibility is by compiling the code with _exactly_ the same build of the rust toolchain. Not a huge deal when statically linking; much harder to enforce when dynamically loading libraries at runtime.

**Comment by nagisa** [comment]
If you have any further questions, feel free to reopen :)

**Comment by nagisa** [comment]
> But as a follow up, so do you mean that as long as my library my_lib is a staticlib and that it's compiled with exactly the same build of the rust toolchain as the code calling fn foo() via libloading, that async code should work fine?

`staticlib` is a different thing altogether. It does _not_ produce dynamic libraries, and the libraries it does produce cannot be loaded with libloading. You need a `cdylib` usually. And, yes, must be exactly the same build of the rust toolchain.
