### ISSUE TITLE
Searching for /etc/ld.so.conf?

### ISSUE THREAD

**Issue by Anivie** [nagisa/rust_libloading#161]
`/etc/ld.so.conf` contains a series of directories, which include a number of configuration files with search paths. Can libloading read the target library search paths from these configuration files?

**Comment by nagisa** [comment]
It all depends on the implementation of the dynamic loader that your binary has set in `INTERP`. That's where the code to search for the libraries and to actually load them lives.

**Comment by polarathene** [comment]
For reference, since it's probably applicable to the majority building on Linux (glibc dynamic linking) with Rust, you should be able to expect and verify the [search logic documented here](https://man7.org/linux/man-pages/man3/dlopen.3.html) for `dlopen()`.

- `DT_RPATH` (ELF attribute)
- `LD_LIBRARY_PATH` (Environment variable)
- `DT_RUNPATH`
- `/etc/ld.so.cache`
- `/lib` + `/usr/lib`

That will only be relevant when the filename given to `dlopen()` does not container a `/` (_which would then be treated as a relative or absolute path and ignore the search paths_).

---

`DT_RPATH` is discouraged, but differs from the rest in that it will be inherited by transitive deps. That is if your program links some libraries and uses the RPATH to resolve the linked libs, when resolving those libs own linked deps, they'd typically start the search again and if their deps are available in other search paths they'd be resolved instead of the ones in the same location. RPATH will prevent that and prioritize that original/inherited RPATH location.

Similar to how `LD_LIBRARY_PATH` works, but it is instead configured into main your binary executable/library. However `DT_RUNPATH` only applies to direct deps, so the equivalent would have any transitive deps you also might bundle also having `DT_RUNPATH` set, or relying on `LD_LIBRARY_PATH` for ensuring precedence.

`DT_RPATH` and `DT_RUNPATH` can be set during build or modify the binary afterwards via tools like `patchelf` which can read/write these changes.

**NOTE:** If you do build for musl target with dynamic linking to use `dlopen()`, then [this behaviour differs](https://github.com/rust-lang/rust/issues/30378#issuecomment-360835215), both `DT_RPATH` and `DT_RUNPATH` are treated the same as `LD_LIBRARY_PATH` apparently (_which is used before those ELF configured paths_).
