### ISSUE TITLE
When running tests outside cargo libloading is not able to find shared object

### ISSUE THREAD

**Issue by jackcmay** [nagisa/rust_libloading#47]
Disclaimer up front, this is probably not a libloading issue but anyone trying to debug tests that use libloading would face the same issue.

I have a test that is loading shared objects and when run via cargo is able to find and load the module.  But, when I try to run the test directly on the command line (or via gdb) the shared object is not found.

std::env is reporting that current_dir and current_exe are the same in both cases so I would expect the same module path passed to libloading would work.

Please advise, thanks!

**Comment by nagisa** [comment]
What cargo does is fiddle with the `LD_LIBRARY_PATH` (and similar) environment variable(s), IIRC. That would make binary able to find shared libraries stashed somewhere inside the `target` directory when run under cargo, but not otherwise.

It is a responsibility of a packager to place the shared libraries in locations where the loader would usually look for shared libraries.

**Comment by jackcmay** [comment]
Thanks!, I found that it was looking for libstd so I resolved this by setting LD_LIBRARY_PATH to: 

`~.rustup/toolchains/stable-x86_64-apple-darwin/lib`
